/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
import (
	"time"
)
// SoftwareInventory This schema defines an inventory of software components.
type SoftwareInventory struct {
	OdataType string `json:"@odata.type"`
	OdataId string `json:"@odata.id"`
	OdataContext string `json:"@odata.context,omitempty"`
	OdataEtag string `json:"@odata.etag,omitempty"`
	Description *string `json:"Description,omitempty"`
	Id string `json:"Id"`
	LowestSupportedVersion *string `json:"LowestSupportedVersion,omitempty"`
	Manufacturer *string `json:"Manufacturer,omitempty"`
	Name string `json:"Name"`
	RelatedItem []IdRef `json:"RelatedItem,omitempty"`
	RelatedItemodataCount *int32 `json:"RelatedItem@odata.count,omitempty"`
	ReleaseDate *time.Time `json:"ReleaseDate,omitempty"`
	SoftwareId string `json:"SoftwareId,omitempty"`
	Status Status `json:"Status,omitempty"`
	UefiDevicePaths []string `json:"UefiDevicePaths,omitempty"`
	Updateable *bool `json:"Updateable"`
	Version *string `json:"Version"`
}
