/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// VolumeType the model 'VolumeType'
type VolumeType string

// List of VolumeType
const (
	VOLUMETYPE_RAW_DEVICE VolumeType = "RawDevice"
	VOLUMETYPE_NON_REDUNDANT VolumeType = "NonRedundant"
	VOLUMETYPE_MIRRORED VolumeType = "Mirrored"
	VOLUMETYPE_STRIPED_WITH_PARITY VolumeType = "StripedWithParity"
	VOLUMETYPE_SPANNED_MIRRORS VolumeType = "SpannedMirrors"
	VOLUMETYPE_SPANNED_STRIPES_WITH_PARITY VolumeType = "SpannedStripesWithParity"
)
