/*
 * Redfish OAPI specification
 *
 * Partial Redfish OAPI specification for a limited client
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// CreateVirtualDiskRequestBody struct for CreateVirtualDiskRequestBody
type CreateVirtualDiskRequestBody struct {
	VolumeType VolumeType `json:"VolumeType"`
	Name string `json:"Name"`
	Drives []IdRef `json:"Drives"`
}
