// Code generated by mockery v1.0.0. DO NOT EDIT.

package controller

import (
	node "bitbucket.com/metamorph/pkg/db/models/node"
	mock "github.com/stretchr/testify/mock"
)

// mockNodedb is an autogenerated mock type for the nodedb type
type mockNodedb struct {
	mock.Mock
}

// GetNodes provides a mock function with given fields:
func (_m *mockNodedb) GetNodes() ([]node.Node, error) {
	ret := _m.Called()

	var r0 []node.Node
	if rf, ok := ret.Get(0).(func() []node.Node); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]node.Node)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
