apiVersion: v1
kind: ConfigMap
metadata:
  name: metamorph-config
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    database:
        type: sqlite
        path: "/opt/metamorph/db/metamorph.db"
    
    controller:
        port : 8080
    
    logger:
        apipath: /opt/metamorph/metamorph_api.log
        controllerpath: /opt/metamorph/metamorph_controller.log
        plugins:
          redfishpluginpath: /opt/metamorph/metamorph_redfishplugin.log
          isogenpluginpath:  /opt/metamorph/metamorph_isogenplugin.log
    
    templates:
        rootdir: /opt/metamorph
        preseed:
            config:  configs/templates/preseed.tmpl
            filepath: preseed/hwe-ubuntu-server.seed
        grub:
            config:  configs/templates/grub.tmpl
            filepath: grub.conf
        isolinux:
            config: configs/templates/hwe_kernel/isolinux_txt.cfg
        cloudinit:
            filepath: 70-metamorph-cloud-init.yaml
        init:
            config: configs/templates/init.sh
            filepath: init.sh
        service:
            config: configs/templates/metamorph-client.service
            filepath: metamorph-client.service
        netplan:
            config: configs/templates/netplan.tmpl
            filepath: 50-cloud-init.yaml
        agent_config:
            config:  configs/templates/agent_config.tmpl
            filepath: agent_config.yaml
    assets:
        rootdir: /opt/metamorph/assets
        agent_binary:
          src:  files/metamorph_agent
          dest: metamorph_agent

    iso:
      rootpath: /opt/metamorph/iso_root
      tempdir: /opt/metamorph/iso_root/isos    
    
    http:
      rootpath: /opt/metamorph/http_root
    
    image:
        url: "http://12.68.220.23:31180/ubuntu-18.04.4-server-amd64.iso"
        checksum: "http://12.68.220.23:31180/ubuntu-18.04.4-server-amd64.iso.md5sum"
    
    provisioning:
        ip : "32.68.220.23"
        port:  3190
        httpport: 31180

    pluginlocation: /opt/metamorph/assets/files


    plugins:
        UpdateFirmware: "metamorph-redfish-plugin"
        ConfigureRAID: "metamorph-redfish-plugin"
        DeployISO: "metamorph-redfish-plugin"
        GetGUUID: "metamorph-redfish-plugin"
        CreateISO: "metamorph-isogen-plugin"
        GetHWInventory: "metamorph-redfish-plugin"
        PowerOff: "metamorph-redfish-plugin"
        PowerOn: "metamorph-redfish-plugin"
        GetPowerStatus: "metamorph-redfish-plugin"
    
    testing:
        inputfile: "/root/go/src/github.com/bm-metamorph/MetaMorph/examples/input.json"
