apiVersion: v1
kind: ConfigMap
metadata:
  name: metamorph-config
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    database:
        type: sqlite
        path: "/opt/metamorph/db/metamorph.db"
    
    controller:
        port : 8080
    
    logger:
        apipath: /opt/metamorph/metamorph_api.log
        controllerpath: /opt/metamorph/metamorph_controller.log
    
    idrac:
        systemID: "System.Embedded.1"
        managerID: "iDRAC.Embedded.1"
        controllerID: "RAID.Slot.6-1"
    
    templates:
        rootdir: /opt/metamorph
        preseed:
            config:  configs/templates/preseed.tmpl
            filepath: preseed/hwe-ubuntu-server.seed
        grub:
            config:  configs/templates/grub.tmpl
            filepath: grub.conf
        isolinux:
            config: configs/templates/hwe_kernel/isolinux_txt.cfg
        init:
            config: configs/templates/init.sh
            filepath: init.sh
        service:
            config: configs/templates/metamorph-client.service
            filepath: metamorph-client.service
        netplan:
            config: configs/templates/netplan.tmpl
            filepath: 50-cloud-init.yaml
        agent_config:
            config:  configs/templates/agent_config.tmpl
            filepath: agent_config.yaml
    assets:
        rootdir: /opt/metamorph/assets
        agent_binary:
          src:  files/metamorph_agent
          dest: metamorph_agent

    iso:
      rootpath: /opt/metamorph/iso_root
      tempdir: /opt/metamorph/iso_root/isos    
    
    http:
      rootpath: /opt/metamorph/http_root
    
    image:
        url: "http://32.68.220.23:31180/ubuntu-18.04.4-server-amd64.iso"
        checksum: "http://32.68.220.23:31180/ubuntu-18.04.4-server-amd64.iso.md5sum"
    
    provisioning:
        ip : "32.68.220.23"
        port:  3190
        httpport: 31180
    
    testing:
        inputfile: "/home/ekuamaj/go/src/github.com/bm-metamorph/Metamorph/examples/input.json"
