---

database:
    type: sqlite
    path: "/tmp/db/metamorph.db"


controller:
    port : 8080

logger:
    apipath: /tmp/metamorph_api.log
    controllerpath: /tmp/metamorph_controller.log
    plugins:
      redfishpluginpath: /tmp/redfish-plugin.log
      isogenpluginpath: /tmp/isogen-plugin.log

templates:
    rootdir: /root/go/src/github.com/manojkva/MetaMorph
    preseed:
        config:  configs/templates/preseed.tmpl
        filepath: preseed/hwe-ubuntu-server.seed
    grub:
        config:  configs/templates/grub.tmpl
        filepath: grub.conf
    isolinux:
        config: configs/templates/hwe_kernel/isolinux_txt.cfg
    init:
        config: configs/templates/init.sh
        filepath: init.sh
    service:
        config: configs/templates/metamorph-client.service
        filepath: metamorph-client.service
    netplan:
        config: configs/templates/netplan.tmpl
        filepath: 50-cloud-init.yaml
    cloudinit:
        filepath: 70-metamorph-cloud-init.yaml
    agent_config:
        config:  configs/templates/agent_config.tmpl
        filepath: agent_config.yaml

assets:
   rootdir: /root/go/src/github.com/manojkva/MetaMorph/assets
   agent_binary:
          src:  files/metamorph_agent
          dest: metamorph_agent

iso:
  rootpath: /tmp/iso_root
  tempdir: /tmp/iso_root/isos


http:
  rootpath: /tmp/http_root

provisioning:
    ip : "32.xx.xx.13"
    port:  3190
    httpport: 31180


pluginlocation: "/root/go/src/github.com/manojkva/MetaMorph/assets/files"

testing:
    inputfile: "/root/go/src/github.com/manojkva/MetaMorph/examples/node1_input.json"

agent:
    node_id: "e415bbbe-be68-4705-aa05-16350e0c8151"
    cntrl_endpoint: "localhost:4040"
    logdir : "/tmp/metamorph"
    temp_dir : "/tmp/metamorph/.tmp"

plugins:
    UpdateFirmware: "metamorph-redfish-plugin"
    ConfigureRAID: "metamorph-redfish-plugin"
    DeployISO: "metamorph-redfish-plugin"
    GetGUUID: "metamorph-redfish-plugin"
    CreateISO: "metamorph-isogen-plugin"
    GetHWInventory: "metamorph-redfish-plugin"
    PowerOff: "metamorph-redfish-plugin"
    PowerOn: "metamorph-redfish-plugin"
    GetPowerStatus: "metamorph-redfish-plugin"
 


